-- SCRIPT THAT DISPLAYS THE AVG TEMPERATURE FROM JULY AND AUGUST, TOP 3 CITIES
SELECT city, AVG(value) AS avg_temp
FROM temperatures
WHERE month IN (7, 8)
GROUP BY city
ORDER BY avg_temp DESC
LIMIT 3;
